<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
     
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

     <link rel="stylesheet" href="public/css/style.css">
     <title>Blog</title>
</head>
<body>
    <header class="bg-primary text-center p-3">
        <h1 class="text-center"><a href="." class="text-white">Location de véhicule</a></h1>
        <nav>
            <a href="?action=inscription" class="btn btn-success" >Inscription</a>
            <a href="?action=connexion" class="btn btn-success">Connexion</a>
        </nav>
    </header>

    <main class="container">
        <?= $content ?? 'pas de vue'; ?>
    </main>

    <footer class="bg-primary text-white text-center p-3 mt-5">
        <a href="" class="text-white text-decoration-none">mentions légales</a>
        <a href="" class="text-white text-decoration-none">Conditions générales de ventes</a>
    </footer>